<?php


namespace services\template\storage;


use basic\BaseMessage;

class Baidu extends BaseMessage
{
    /**
     * 初始化
     * @param array $config
     * @return mixed|void
     */
    protected function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
    }

    /**
     * 发送模板消息
     * @param string $templateId
     * @param array $data
     * @return mixed|void
     */
    public function send(string $templateId, array $data = [])
    {
        // TODO: Implement send() method.
    }

    /**
     * 添加模板消息
     * @param string $shortId
     * @return mixed|void
     */
    public function add(string $shortId)
    {
        // TODO: Implement add() method.
    }

    /**
     * 删除模板消息
     * @param string $templateId
     * @return mixed|void
     */
    public function delete(string $templateId)
    {
        // TODO: Implement delete() method.
    }

    /**
     * 模板消息列表
     * @return mixed|void
     */
    public function list()
    {
        // TODO: Implement list() method.
    }
}
